import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import "./Profile.css";
import "./Faceit.css";
const UserProfile = ({ user }) => {
    const canShowFaceitLink = !!user.isFaceitLinked && !!user.faceitNickname;
    const faceitProfileUrl = user.faceitNickname
        ? `https://www.faceit.com/ru/players/${user.faceitNickname}`
        : "";
    const steamProfileUrl = user.steamUrl || (user.isSteamLinked ? "#" : null);
    const telegramProfileUrl = user.telegramUrl || (user.isTelegramLinked ? "#" : null);
    return (_jsxs("div", { className: "profile-card clean-profile", style: { position: "relative" }, children: [_jsxs("div", { className: "profile-header", children: [_jsx("img", { className: "profile-avatar", src: user.avatarUrl || "https://ui-avatars.com/api/?name=User", alt: "\u0410\u0432\u0430\u0442\u0430\u0440" }), _jsxs("div", { className: "profile-main-info", children: [_jsx("div", { className: "profile-nickname", children: canShowFaceitLink ? (_jsx("a", { href: faceitProfileUrl, target: "_blank", rel: "noopener noreferrer", title: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u043F\u0440\u043E\u0444\u0438\u043B\u044C \u043D\u0430 Faceit", children: user.faceitNickname })) : (user.faceitNickname || user.name) }), _jsxs("div", { className: "profile-id", children: ["ID#", user.id, user.faceitId && (_jsxs("span", { className: "faceit-id", children: [" ", "| Faceit ID: ", user.faceitId] }))] })] }), canShowFaceitLink && (_jsx("a", { href: faceitProfileUrl, target: "_blank", rel: "noopener noreferrer", className: "faceit-icon-link", title: "\u041F\u0440\u043E\u0444\u0438\u043B\u044C \u043D\u0430 Faceit", children: _jsx("img", { src: "/images/\u0444\u0435\u0439\u0441\u0438\u0442.jpg", alt: "Faceit", className: "faceit-icon" }) }))] }), _jsxs("div", { className: "social-accounts", children: [canShowFaceitLink && (_jsx("a", { href: faceitProfileUrl, target: "_blank", rel: "noopener noreferrer", className: "social-icon", title: "\u041F\u0440\u043E\u0444\u0438\u043B\u044C \u043D\u0430 Faceit", children: _jsx("img", { src: "/images/\u0444\u0435\u0439\u0441\u0438\u0442.jpg", alt: "Faceit" }) })), user.isSteamLinked && steamProfileUrl && (_jsx("a", { href: steamProfileUrl, target: "_blank", rel: "noopener noreferrer", className: "social-icon", title: "\u041F\u0440\u043E\u0444\u0438\u043B\u044C \u0432 Steam", children: _jsx("img", { src: "/images/\u0441\u0442\u0438\u043C.png", alt: "Steam" }) })), user.isTelegramLinked && telegramProfileUrl && (_jsx("a", { href: telegramProfileUrl, target: "_blank", rel: "noopener noreferrer", className: "social-icon", title: "\u041F\u0440\u043E\u0444\u0438\u043B\u044C \u0432 Telegram", children: _jsx("img", { src: "/images/\u0442\u0433.png", alt: "Telegram" }) }))] })] }));
};
export default UserProfile;
